# Generated by Django 4.2.4 on 2023-08-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modificators',
            options={'ordering': ('name',), 'verbose_name': 'Модификатор', 'verbose_name_plural': 'Модификаторы'},
        ),
    ]
